name: Build with vcpkg

on:
  workflow_dispatch:

env:
  VCPKG_ROOT: ./vcpkg

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows
          - runs-on: windows-latest
            triplet: x64-windows-static
          - runs-on: windows-latest
            triplet: x86-windows-static
          - runs-on: windows-11-arm
            triplet: arm64-windows-static

          # macOS
          - runs-on: macos-15-intel
            triplet: x64-osx-release
          - runs-on: macos-latest
            triplet: arm64-osx-release

          # Linux
          - runs-on: ubuntu-latest
            triplet: x64-linux-release
          - runs-on: ubuntu-24.04-arm
            triplet: arm-linux-release
          - runs-on: ubuntu-24.04-arm
            triplet: arm64-linux-release

    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.triplet }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install ARMv7 cross compiler
        if: matrix.triplet == 'arm-linux-release'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Install dependencies with vcpkg
        shell: bash
        run: |
          ./$VCPKG_ROOT/bootstrap-vcpkg.sh
          $VCPKG_ROOT/vcpkg install --triplet=${{ matrix.triplet }}

      - name: Upload vcpkg_installed
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_installed-${{ matrix.triplet }}
          path: ${{ github.workspace }}/vcpkg_installed/${{ matrix.triplet }}
